### ISSUE TITLE
Why is .git included in the source?

### ISSUE THREAD

**Issue by carlo-fontanos** [josegonzalez/php-dotenv#43]
After installing via composer, when I navigate to `vendor\josegonzalez\dotenv` the **.git** folder is present.

I cannot commit this folder to my own repo because this folder has its own repo.

**Comment by josegonzalez** [comment]
Dunno, sounds like a composer issue. I normally ignore the vendor dir for deployed apps.

This might have to do with our `.gitattributes` file. If you can figure out a fix, I'll merge the pull request :)

**Comment by pxgamer** [comment]
Are you using `--prefer-source` or using `dev-master` as in the README?

These will clone the repository, rather than downloading the `.zip`/`.tar.gz` archive (which won't contain the `.git` directory).

<details>
<summary>Example Install</summary>

![](https://image.prntscr.com/image/Mq7iAZJvR7K8xbBEHxSDsA.png)

</details>

**Comment by yCodeTech** [comment]
@carlo-fontanos FYI, it's not recommended to commit any dependencies in the `vendor` directory to your repo. It's a big Composer **no-no**.  There's a [whole page on it](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) explaining the issues. However, the page also gives a few options if you really *must* do it. But generally-speaking, you don't need to, nor should you commit dependencies to a repo, it's just impractical, and is probably considered as bad practice.
